name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Elixir 1.15 with compatible OTP versions (24-26)
          - elixir: "1.15"
            otp: "24"
          - elixir: "1.15"
            otp: "25"
          - elixir: "1.15"
            otp: "26"
          
          # Elixir 1.16 with compatible OTP versions (24-26)
          - elixir: "1.16"
            otp: "24"
          - elixir: "1.16"
            otp: "25"
          - elixir: "1.16"
            otp: "26"
          
          # Elixir 1.17 with compatible OTP versions (25-27)
          - elixir: "1.17"
            otp: "25"
          - elixir: "1.17"
            otp: "26"
          - elixir: "1.17"
            otp: "27"
          
          # Elixir 1.18 with compatible OTP versions (25-27)
          - elixir: "1.18"
            otp: "25"
          - elixir: "1.18"
            otp: "26"
          - elixir: "1.18"
            otp: "27"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile
        run: |
          if [ "${{ matrix.elixir }}" = "1.18" ] && [ "${{ matrix.otp }}" = "27" ]; then
            mix compile --warnings-as-errors
          else
            mix compile
          fi

      - name: Run tests
        run: mix test

      - name: Generate coverage report
        run: mix test --cover --export-coverage default
        continue-on-error: true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: matrix.elixir == '1.18' && matrix.otp == '27'
        with:
          name: coverage-report
          path: cover/
